fastlane_require "dotenv"
default_platform(:ios)
before_all do
  Dotenv.load "fastlane.env.secret"
end
platform :ios do
  before_all do
    Dotenv.load "fastlane.env"
    Dotenv.load "fastlane.env.ios"
  end

desc "Create on Developer Portal and App Store Connect"
  lane :create_app do 
   create_app_online # produce  
end

desc "Sync singing"
  lane :signing do
    sync_code_signing # match
    mapping = lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
     update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
     )
end

desc "Build binary"
  lane :build do
   signing
   build_ios_app #gym
end 

desc "Release"
  lane :release do
  ensure_git_status_clean
  ensure_git_branch
   build
   upload_to_app_store # deliver
   end
end
